feat: add new structure of `telegram` notifier
Alwatr/notifier pull request #242
Opened 2024-10-21 09:45 UTC by mohammadhonarvar

2024-10-22 08:26 UTC, AliMD commented on .github/dependabot.yml
add docker plz

2024-10-22 09:09 UTC, mohammadhonarvar commented on .github/dependabot.yml
Hi there.
I'm sorry for not getting back to you sooner.
I've added `deploy` directory and I've added `Dockerfile` in `telegram` directory.

Please check the `env` in `deploy`.

2024-10-22 11:09 UTC, AliMD commented on .github/dependabot.yml
منظورم همین package-ecosystem: docker بعد
مرسی
همون ویس تو گروه راحت تره
درضمن there هم خودتی

2024-10-24 11:31 UTC, AliMD commented on .github/workflows/codeql.yaml
> +    - notifier-api: '0 7 * */2 *'
خدایی چرا اسم این عوض شده! 😄 اینجوری که کار نمیکنه

2024-10-24 11:40 UTC, AliMD requested changes
مرسی
تغییرات رو یا خودم انجام میدم یا در گروه ویس میدم

2024-10-25 13:42 UTC, merged