feat: add `telegram-message-sender` package
Alwatr/notifier pull request #252
Opened 2024-10-26 07:45 UTC by mohammadhonarvar

2024-10-26 08:32 UTC, AliMD requested changes

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/.dockerignore
چرا اینو داره؟!

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/.gitignore
و این؟!

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/README.md
اسمش خوب نیست
باهم صحبت کنیم و عکس کن
همه جا notify گذاشتیم
و بعد علاوه بر telegram چیزایی دیگه هم میاد

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/package.json
> +  "name": "telegram-message-sender",
چرا نامس اینجوریه؟!

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/package.json
> +  "version": "1.0.0",
-0

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/package.json
> +  "private": true,
چرا پرایوت؟!

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  async send(categoryId: string, message: string, markdown?: true) {
notify

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  constructor(config: Partial<FetchOptions>) {
لطفا کانفیگ اصلی api آدرس رو حذف کن و فقط base address باشه و خودت /notify رو بفهش اضافه کن

2024-10-26 08:32 UTC, AliMD commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  async send(categoryId: string, message: string, markdown?: true) {
کتگوری باید بره تو config ولی اینجا بشه کانفیگ رو در پارامتر دوم optional تغییر داد طوری که رو اصلی مرج بشه
پارامتر اول و اصلی فقط پیام

2024-10-26 08:44 UTC, mohammadhonarvar commented on packages/telegram-message-sender/.dockerignore
حذف شد

2024-10-26 08:47 UTC, mohammadhonarvar commented on packages/telegram-message-sender/package.json
> +  "name": "telegram-message-sender",
اسمش رو باید ببینیم چی باشه

2024-10-26 08:47 UTC, mohammadhonarvar commented on packages/telegram-message-sender/README.md
اکی

2024-10-26 08:50 UTC, mohammadhonarvar commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  async send(categoryId: string, message: string, markdown?: true) {
markdown چی میشه؟

2024-10-26 08:51 UTC, mohammadhonarvar commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  constructor(config: Partial<FetchOptions>) {
تایپ کانفیگ FetchOptions هست، کلا تغییرش بدم و اون کلیدایی که فقط لازم هست رو بدم؟ با مقادیری که لازمه

2024-10-26 09:16 UTC, mohammadhonarvar commented on packages/telegram-message-sender/README.md
اسمش رو باید ببینیم چی باشه

2024-10-26 09:45 UTC, mohammadhonarvar commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  constructor(config: Partial<FetchOptions>) {
کلا config رو عوض کردم با توجه به چیزی که گفتید

2024-10-26 09:46 UTC, mohammadhonarvar commented on packages/telegram-message-sender/src/telegram-message-sender.ts
> +  async send(categoryId: string, message: string, markdown?: true) {
اینم اکی شد و الان دو تا وردی داریم که اولیش  message هست
اون markdown  هم که پرسیده بودم اکی شد

2024-10-28 11:54 UTC, AliMD commented on packages/telegram-message-sender/src/main.ts
> +logger.banner(__package_name__);
!!

2024-10-28 12:17 UTC, AliMD commented on packages/telegram-message-sender/package.json
> +    "alwatr": "^2.0.3",
این چرا تو dev هستش!

2024-10-28 13:42 UTC, merged